eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8006
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
    api-c:
      path: /api-c/**
      serviceId: eureka-client
    api-d:
      path: /api-d/**
      serviceId: service-swagger
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000